<?php return array(
    'root' => array(
        'name' => 'luminovang/luminova',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '439f88a14d217e79c497907288f62f227bc4edb6',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'luminovang/framework' => array(
            'pretty_version' => '2.9.6',
            'version' => '2.9.6.0',
            'reference' => '7b24ec5fea431f19df82dbc7e05114641f4402fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../luminovang/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'luminovang/luminova' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '439f88a14d217e79c497907288f62f227bc4edb6',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
