<?php return array(
    'root' => array(
        'name' => 'luminovang/luminova',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'ca74ff3d965f31b753e112196850c7001061d6f6',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'luminovang/framework' => array(
            'pretty_version' => '2.9.2',
            'version' => '2.9.2.0',
            'reference' => '68c35f60ba64b28229b23b3a0cec392c44151f45',
            'type' => 'library',
            'install_path' => __DIR__ . '/../luminovang/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'luminovang/luminova' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'ca74ff3d965f31b753e112196850c7001061d6f6',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
